services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-javascript:stable-1
    init: true
    ports: 
      - "3000:3000"
      - "1234:1234"
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

