export const data_source_Column = [
  {
    id: 'data_source_name',
    label: 'Data Source Name',
    minWidth: 240,
    color: '#FFFFFF',
    background: '#485E7C',
    textAlign: 'center',
  },
  {
    id: 'integration_name',
    label: 'Integration',
    minWidth: 162,
    color: '#FFFFFF',
    background: '#485E7C',
    textAlign: 'center',
  },
  {
    id: 'ip_address',
    label: 'IP Address',
    minWidth: 140,
    color: '#FFFFFF',
    background: '#485E7C',
    textAlign: 'center',
  },
  {
    id: 'data_type',
    label: 'Data Type',
    minWidth: 198,
    color: '#FFFFFF',
    background: '#485E7C',
    textAlign: 'center',
  },
  {
    id: 'asset_type',
    label: 'Asset Type',
    minWidth: 198,
    color: '#FFFFFF',
    background: '#485E7C',
    textAlign: 'center',
  },
  {
    id: 'attack_lifecycle',
    label: 'ATT&CK Lifecycle',
    minWidth: 242,
    color: '#FFFFFF',
    background: '#485E7C',
    textAlign: 'center',
  },
  {
    id: 'data_retention_days',
    label: 'Data Retention',
    minWidth: 134,
    color: '#FFFFFF',
    background: '#485E7C',
    textAlign: 'center',
  },
  {
    id: 'data_location',
    label: 'Data Location',
    minWidth: 140,
    color: '#FFFFFF',
    background: '#485E7C',
    textAlign: 'center',
  },
  {
    id: 'collection_layer',
    label: 'Collection Layer',
    minWidth: 159,
    color: '#FFFFFF',
    background: '#485E7C',
    textAlign: 'center',
  },
  {
    id: 'department',
    label: 'Department',
    minWidth: 140,
    color: '#FFFFFF',
    background: '#485E7C',
    textAlign: 'center',
  },
  {
    id: 'action',
    label: '',
    minWidth: 68,
    color: '#FFFFFF',
    background: '#485E7C',
    textAlign: 'center',
  },
]

export const crown_jewel_Column = [
  {
    id: 'asset_id',
    label: 'Asset Id',
    minWidth: 113,
    color: '#FFFFFF',
  },
  {
    id: 'asset_name',
    label: 'Asset Name',
    minWidth: 120,
    color: '#FFFFFF',
  },
  {
    id: 'data_source_name',
    label: 'Data Source Name',
    minWidth: 240,
    color: '#FFFFFF',
  },
  {
    id: 'integration_name',
    label: 'Integration',
    minWidth: 162,
    color: '#FFFFFF',
  },
  {
    id: 'asset',
    label: 'Asset Criticality',
    minWidth: 140,
    color: '#FFFFFF',
  },
  {
    id: 'public_facing_yes_or_no',
    label: 'Public Facing',
    minWidth: 140,
    color: '#FFFFFF',
  },
  {
    id: 'operational_impact',
    label: 'Operational Impact',
    minWidth: 140,
    color: '#FFFFFF',
  },
  {
    id: 'financial_impact',
    label: 'Financial Impact',
    minWidth: 140,
    color: '#FFFFFF',
  },
  {
    id: 'reputation_impact',
    label: 'Reputation Impact',
    minWidth: 140,
    color: '#FFFFFF',
  },
  {
    id: 'strategic_importance',
    label: 'Strategic Importance',
    minWidth: 140,
    color: '#FFFFFF',
  },
  {
    id: 'regulatory_compliance',
    label: 'Regulatory Compliance',
    minWidth: 140,
    color: '#FFFFFF',
  },
  {
    id: 'total_score',
    label: 'Total Score',
    minWidth: 140,
    color: '#FFFFFF',
  },
  {
    id: 'action',
    label: '',
    minWidth: 68,
    color: '#FFFFFF',
  },
]

export const data_source_value = [
  {
    id: 1,
    assetid: 'AS12345',
    assetname: 'Asset 1',
    dsname: 'Splunk DS log1',
    integration: 'Splunk',
    asset: '8',
    publicface: 'Yes',
    operational: '10',
    financial: '30',
    seputation: '8',
    strategic: '5',
    regulatory: '6',
    total: '10',
  },
  {
    id: 1,
    assetid: 'ID13579',
    assetname: 'Asset 1',
    dsname: 'Splunk DS log2',
    integration: 'Elastic',
    asset: '2',
    publicface: 'No',
    operational: '20',
    financial: '20',
    seputation: '5',
    strategic: '23',
    regulatory: '6',
    total: '10',
  },
]
